[tool.poetry]
name = "yui"
version = "0.0.0"
description = "YUI is Multi-purpose Slack Bot."
authors = ["Kim Jin Su <item4_hun@hotmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.5"
cchardet = "^2.1"
async-timeout = "^3.0"
sqlalchemy = "^1.2"
sqlalchemy-utils = "^0.33.6"
alembic = "^1.0"
click = "^7.0"
toml = "^0.10.0"
aiocron = "^1.3"
fuzzywuzzy = {version = "^0.17.0",extras = ["speedup"]}
lxml = "^4.2"
cssselect = "^1.0"
babel = "^2.6"
ujson = "^1.35"
feedparser = "^5.2"
attrdict = "^2.0"
pytz = "^2018.7"
tzlocal = "^1.5"
python-dateutil = "^2.8" 
psycopg2-binary = "^2.7"
pyppeteer = "^0.0.25"
asyncio-contextmanager = "^1.0"
attrs = "^19.1"
sympy = "^1.3"
tossi = "^0.3.1"
codecov = {version = "^2.0",optional = true}
fake_useragent = "^0.1.11"
scipy = "^1.2"

[tool.poetry.dev-dependencies]
mypy = "^0.700"
pytest = "^4.0"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.6"
aioresponses = "^0.6"
flake8 = "^3.6"
flake8-import-order = "^0.18.0"
freezegun = "^0.3.11"

[tool.poetry.extras]
travis-ci = ["codecov"]

[tool.poetry.scripts]
yui = "yui.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
